#!/usr/bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          20

bspc config normal_border_color "#484848"
bspc config focused_border_color "#1F8999"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true



#autostart

sxhkd &
picom --config $HOME/.config/picom/picom.conf &
dunst &
polybar &



feh --bg-fill $HOME/k.jpg
